"use client"

import React, { useState } from 'react';
import { LightTable as Table } from '@/src/components/LightTable';
import { Badge } from '@/src/components/Badge';
import { Button } from '@/src/components/Button';
import { Select, Input } from '@/src/components/Input';
import { Modal } from '@/src/components/Modal';
import { Plus, Loader2, FileText, ChevronRight } from 'lucide-react';
import { Card } from '@/src/components/Card';
import { usePayrollRuns } from '@/src/hooks/usePayroll';
import { PayrollRun } from '@/src/types/staff';
import { useRouter } from 'next/navigation';

export default function PayrollManagement() {
  const router = useRouter();
  const [yearFilter, setYearFilter] = useState('');
  const [statusFilter, setStatusFilter] = useState('');
  
  const [isAddModalOpen, setIsAddModalOpen] = useState(false);
  const [formData, setFormData] = useState({
    year: new Date().getFullYear(),
    month: new Date().getMonth() + 1,
    period_start: '',
    period_end: '',
    notes: ''
  });

  const { payrollRuns, isLoading, createPayrollRun, isCreating } = usePayrollRuns({
    year: yearFilter || undefined,
    status: statusFilter || undefined,
  });

  const handleCreateRun = () => {
    if (!formData.period_start || !formData.period_end) {
      alert('Please fill period start and end dates');
      return;
    }
    createPayrollRun(formData, {
      onSuccess: () => setIsAddModalOpen(false)
    });
  };

  const columns = [
    { 
      key: 'period', 
      header: 'PERIOD',
      render: (_: any, row: PayrollRun) => (
        <span className="font-bold text-slate-900 text-sm">
          {row.month}/{row.year}
        </span>
      )
    },
    { 
      key: 'dates', 
      header: 'DATES',
      render: (_: any, row: PayrollRun) => (
        <span className="text-sm font-medium text-slate-600">
          {row.period_start} — {row.period_end}
        </span>
      )
    },
    { 
      key: 'staff', 
      header: 'STAFF',
      render: (_: any, row: PayrollRun) => (
        <span className="text-sm font-medium text-slate-600">
          {(row.lines || []).length} staff
        </span>
      )
    },
    { 
      key: 'status', 
      header: 'STATUS',
      render: (v: string) => (
        <Badge 
          variant={v === 'paid' ? 'success' : v === 'draft' ? 'warning' : 'secondary'} 
          size="sm" 
          className="font-bold uppercase tracking-widest text-[9px] border-none px-3 py-0.5 rounded-full"
        >
          {v}
        </Badge>
      )
    },
    {
      key: 'generated_by',
      header: 'GENERATED BY',
      render: (_: any, row: PayrollRun) => (
        <span className="text-sm font-medium text-slate-600">{row.generated_by_name || '---'}</span>
      )
    },
    {
      key: 'date',
      header: 'DATE',
      render: (_: any, row: PayrollRun) => (
        <span className="text-sm font-medium text-slate-600">
          {row.generated_at ? new Date(row.generated_at).toISOString().split('T')[0] : '---'}
        </span>
      )
    },
    {
      key: 'actions',
      header: '',
      align: 'right' as const,
      render: (_: any, row: PayrollRun) => (
        <button 
          onClick={() => router.push(`/dashboard/payroll/${row.id}`)}
          className="p-1 px-3 border border-slate-200 bg-white hover:bg-slate-50 text-slate-900 rounded-lg transition-all"
        >
          <ChevronRight className="w-4 h-4" />
        </button>
      )
    }
  ];

  return (
    <div className="animate-fade-in -m-6 p-6 min-h-screen bg-[#f4f6f8] font-sans text-slate-800 space-y-6">
      <div className="flex items-center justify-between">
        <h1 className="text-xl font-bold text-slate-900 tracking-tight">Payroll Runs</h1>
      </div>

      <div className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden">
        <div className="px-5 py-4 border-b border-slate-100 flex flex-wrap items-center justify-between gap-4">
          <div className="flex flex-wrap items-center gap-3">
             <span className="text-sm font-bold text-slate-800 mr-2">Payroll Runs</span>
              <Select
                value={yearFilter}
                onChange={(e) => setYearFilter(e.target.value)}
                className="bg-white border-slate-200 text-slate-900 w-32 h-9 text-sm font-medium"
                options={[
                  { value: '', label: 'All Year' },
                  { value: '2026', label: '2026' },
                  { value: '2025', label: '2025' }
                ]}
              />
              <Select
                value={statusFilter}
                onChange={(e) => setStatusFilter(e.target.value)}
                className="bg-white border-slate-200 text-slate-900 w-32 h-9 text-sm font-medium"
                options={[
                  { value: '', label: 'All Status' },
                  { value: 'draft', label: 'Draft' },
                  { value: 'finalized', label: 'Finalized' },
                  { value: 'paid', label: 'Paid' }
                ]}
              />
          </div>
          <button 
            onClick={() => setIsAddModalOpen(true)}
            className="bg-violet-600 hover:bg-violet-700 text-white flex items-center justify-center rounded-lg px-4 h-9 text-sm font-bold shadow-sm transition-colors"
          >
            <Plus className="w-4 h-4 mr-2 text-white" />
            Create Run
          </button>
        </div>
        
        <div className="min-h-[400px]">
          {isLoading ? (
            <div className="flex flex-col items-center justify-center p-40">
              <Loader2 className="animate-spin text-violet-600 w-10 h-10" />
            </div>
          ) : !payrollRuns || payrollRuns.length === 0 ? (
            <div className="p-20 text-center flex flex-col items-center gap-3">
              <FileText className="w-12 h-12 text-slate-200"/>
              <p className="text-slate-500 font-medium text-sm">No payroll runs found.</p>
            </div>
          ) : (
            <Table columns={columns} data={payrollRuns || []} className="border-none" />
          )}
        </div>
      </div>

      <Modal theme="light"
        isOpen={isAddModalOpen}
        onClose={() => setIsAddModalOpen(false)}
        title="Create Payroll Run"
        size="md"
        footer={
          <div className="flex gap-3 w-full sm:w-auto mt-4">
            <Button variant="outline" onClick={() => setIsAddModalOpen(false)} className="flex-1 sm:flex-none h-11 border-slate-200 text-slate-700 font-bold px-8">Cancel</Button>
            <Button variant="primary" onClick={handleCreateRun} isLoading={isCreating} className="flex-1 sm:flex-none px-10 bg-violet-600 hover:bg-violet-700 text-white border-none shadow-none font-bold h-11">Create Run</Button>
          </div>
        }
      >
        <div className="space-y-6 pt-4">
          <div className="grid grid-cols-2 gap-5">
            <Input 
              label="YEAR *" type="number"
              value={formData.year.toString()}
              onChange={(e) => setFormData({...formData, year: parseInt(e.target.value)})}
              className="bg-white border-slate-200 text-slate-900"
            />
            <Input 
              label="MONTH *" type="number"
              value={formData.month.toString()}
              onChange={(e) => setFormData({...formData, month: parseInt(e.target.value)})}
              className="bg-white border-slate-200 text-slate-900"
            />
          </div>
          
          <div className="grid grid-cols-2 gap-5">
            <Input 
              label="PERIOD START *" type="date"
              value={formData.period_start}
              onChange={(e) => setFormData({...formData, period_start: e.target.value})}
              className="bg-white border-slate-200 text-slate-900"
            />
            <Input 
              label="PERIOD END *" type="date"
              value={formData.period_end}
              onChange={(e) => setFormData({...formData, period_end: e.target.value})}
              className="bg-white border-slate-200 text-slate-900"
            />
          </div>

          <div className="flex flex-col gap-2">
            <label className="text-[11px] font-bold text-slate-500 uppercase tracking-widest ml-1">NOTES</label>
            <textarea
              placeholder="Optional notes"
              value={formData.notes}
              onChange={(e) => setFormData({...formData, notes: e.target.value})}
              className="w-full min-h-[100px] p-3 rounded-xl border border-slate-200 bg-white text-slate-900 text-sm focus:outline-none focus:ring-2 focus:ring-violet-600/20 transition-all resize-none"
            />
          </div>
        </div>
      </Modal>
    </div>
  );
}
